image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/greta_formation/php_website_nanasite

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

test:
  stage: test
  script:
    - docker pull $CONTAINER_IMAGE
    - docker run -d --name test_container $CONTAINER_IMAGE
    - docker exec test_container php -l /var/www/html/index.php